app = "promptu-kafka-eds"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  KAFKA_ZOOKEEPER_CONNECT="promptu-zookeeper-eds.fly.dev:2181"
  KAFKA_ADVERTISED_LISTENERS="INSIDE://:9092,OUTSIDE://promptu-kafka-eds.fly.dev:9094"
  KAFKA_LISTENERS="INSIDE://:9092,OUTSIDE://:9094"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME="INSIDE"
  KAFKA_HEAP_OPTS="-Xmx1024M -Xms1024M"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="1"
  KAFKA_DELETE_TOPIC_ENABLE="true"

[build]
  image = "confluentinc/cp-kafka:7.3.2"

[mounts]
  destination = "/data"
  source = "kafka_data"

[[services]]
  internal_port = 9092
  protocol = "tcp"

  [[services.ports]]
    port = 9094

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
