app = "promptu-zookeeper-eds"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "confluentinc/cp-zookeeper:7.3.2"
  [build.args]
    ALLOW_ANONYMOUS_LOGIN="yes"

[env]
  ZOOKEEPER_DATA_DIR="/data"
  ZOOKEEPER_CLIENT_PORT="2181"

[mounts]
  destination = "/data"
  source = "zookeeper_data"

[[services]]
  internal_port = 2181
  protocol = "tcp"

  [[services.ports]]
    port = "2181"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"


